name: Build and Deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      QTWEBENGINE_CHROMIUM_FLAGS: --no-sandbox
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install the dependencies
        run: |
          npm install
          sudo apt-get update
          sudo apt-get install -y wget python xz-utils xdg-utils libnss3
          sudo apt-get clean
          sudo wget --no-check-certificate -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin
          echo "/opt/calibre" >> $GITHUB_PATH
      - name: Build docs
        run: npx honkit build
      - name: Build PDF
        run: npx honkit pdf ./ ./book.pdf
      - name: Build ePub
        run: npx honkit epub ./ ./book.epub
      - name: Build Mobi
        run: npx honkit mobi ./ ./book.mobi
      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: documents.zip
          path: |
            book.pdf
            book.epub
            book.mobi
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _book
